"""
University Data Population Script

Populates universities_master and colleges_cache tables with:
- Top Need-Blind schools for Internationals
- Major US Public Universities
- Hidden gems with strong programs

All entries include pre-computed embeddings using text-embedding-004.

Usage:
    cd backend
    python scripts/populate_universities.py
"""

import asyncio
import json
import logging
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, asdict

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


@dataclass
class UniversityEntry:
    """University data for population."""
    name: str
    state: str
    campus_setting: str  # URBAN, SUBURBAN, RURAL, TOWN
    
    # Admission stats
    acceptance_rate: float  # 0.0-1.0
    median_gpa: Optional[float] = None
    sat_25th: Optional[int] = None
    sat_75th: Optional[int] = None
    act_25th: Optional[int] = None
    act_75th: Optional[int] = None
    
    # Tuition (USD per year)
    tuition_in_state: Optional[float] = None
    tuition_out_of_state: Optional[float] = None
    tuition_international: Optional[float] = None
    
    # Financial aid
    need_blind_domestic: bool = True
    need_blind_international: bool = False
    meets_full_need: bool = False
    avg_aid_package: Optional[float] = None
    
    # Metadata
    is_public: bool = False
    official_url: Optional[str] = None
    description: str = ""
    
    # Major rankings (for Computer Science)
    cs_ranking: Optional[int] = None
    engineering_ranking: Optional[int] = None


# =============================================================================
# UNIVERSITY DATA (50+ High-Value Universities)
# =============================================================================

UNIVERSITIES: List[UniversityEntry] = [
    # =========================================================================
    # TIER 1: Need-Blind for International Students (7 schools)
    # =========================================================================
    UniversityEntry(
        name="Harvard University",
        state="MA",
        campus_setting="URBAN",
        acceptance_rate=0.032,
        median_gpa=3.95,
        sat_25th=1480,
        sat_75th=1580,
        act_25th=34,
        act_75th=36,
        tuition_out_of_state=59076,
        tuition_international=59076,
        need_blind_domestic=True,
        need_blind_international=True,
        meets_full_need=True,
        avg_aid_package=60000,
        official_url="https://www.harvard.edu",
        description="Ivy League research university in Cambridge, MA. Strong in all fields.",
        cs_ranking=14,
    ),
    UniversityEntry(
        name="Yale University",
        state="CT",
        campus_setting="URBAN",
        acceptance_rate=0.045,
        median_gpa=3.95,
        sat_25th=1470,
        sat_75th=1570,
        act_25th=33,
        act_75th=35,
        tuition_out_of_state=62250,
        tuition_international=62250,
        need_blind_domestic=True,
        need_blind_international=True,
        meets_full_need=True,
        avg_aid_package=58000,
        official_url="https://www.yale.edu",
        description="Ivy League research university in New Haven, CT. Strong liberal arts.",
        cs_ranking=20,
    ),
    UniversityEntry(
        name="Princeton University",
        state="NJ",
        campus_setting="SUBURBAN",
        acceptance_rate=0.040,
        median_gpa=3.95,
        sat_25th=1500,
        sat_75th=1580,
        act_25th=34,
        act_75th=36,
        tuition_out_of_state=59710,
        tuition_international=59710,
        need_blind_domestic=True,
        need_blind_international=True,
        meets_full_need=True,
        avg_aid_package=62000,
        official_url="https://www.princeton.edu",
        description="Ivy League research university in Princeton, NJ. Strong in STEM and humanities.",
        cs_ranking=8,
    ),
    UniversityEntry(
        name="Massachusetts Institute of Technology",
        state="MA",
        campus_setting="URBAN",
        acceptance_rate=0.039,
        median_gpa=3.95,
        sat_25th=1510,
        sat_75th=1580,
        act_25th=35,
        act_75th=36,
        tuition_out_of_state=60156,
        tuition_international=60156,
        need_blind_domestic=True,
        need_blind_international=True,
        meets_full_need=True,
        avg_aid_package=55000,
        official_url="https://www.mit.edu",
        description="World-leading technology and research university. Top programs in CS, engineering.",
        cs_ranking=1,
        engineering_ranking=1,
    ),
    UniversityEntry(
        name="Amherst College",
        state="MA",
        campus_setting="SUBURBAN",
        acceptance_rate=0.070,
        median_gpa=3.90,
        sat_25th=1430,
        sat_75th=1550,
        act_25th=32,
        act_75th=35,
        tuition_out_of_state=66110,
        tuition_international=66110,
        need_blind_domestic=True,
        need_blind_international=True,
        meets_full_need=True,
        avg_aid_package=58000,
        official_url="https://www.amherst.edu",
        description="Top liberal arts college. Small class sizes, open curriculum.",
        cs_ranking=None,
    ),
    UniversityEntry(
        name="Dartmouth College",
        state="NH",
        campus_setting="RURAL",
        acceptance_rate=0.061,
        median_gpa=3.90,
        sat_25th=1440,
        sat_75th=1560,
        act_25th=32,
        act_75th=35,
        tuition_out_of_state=65511,
        tuition_international=65511,
        need_blind_domestic=True,
        need_blind_international=True,
        meets_full_need=True,
        avg_aid_package=55000,
        official_url="https://home.dartmouth.edu",
        description="Ivy League college in rural New Hampshire. Strong undergrad focus.",
        cs_ranking=30,
    ),
    UniversityEntry(
        name="Bowdoin College",
        state="ME",
        campus_setting="SUBURBAN",
        acceptance_rate=0.085,
        median_gpa=3.85,
        sat_25th=1380,
        sat_75th=1530,
        act_25th=32,
        act_75th=34,
        tuition_out_of_state=64410,
        tuition_international=64410,
        need_blind_domestic=True,
        need_blind_international=True,
        meets_full_need=True,
        avg_aid_package=52000,
        official_url="https://www.bowdoin.edu",
        description="Top liberal arts college in Maine. Beautiful coastal campus.",
        cs_ranking=None,
    ),
    
    # =========================================================================
    # TIER 2: Elite Private Universities (Need-Aware but Generous)
    # =========================================================================
    UniversityEntry(
        name="Stanford University",
        state="CA",
        campus_setting="SUBURBAN",
        acceptance_rate=0.037,
        median_gpa=3.95,
        sat_25th=1500,
        sat_75th=1580,
        act_25th=34,
        act_75th=36,
        tuition_out_of_state=61731,
        tuition_international=61731,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=58000,
        official_url="https://www.stanford.edu",
        description="Silicon Valley research university. Top programs in CS, engineering, business.",
        cs_ranking=2,
        engineering_ranking=2,
    ),
    UniversityEntry(
        name="California Institute of Technology",
        state="CA",
        campus_setting="SUBURBAN",
        acceptance_rate=0.032,
        median_gpa=3.95,
        sat_25th=1530,
        sat_75th=1580,
        act_25th=35,
        act_75th=36,
        tuition_out_of_state=63255,
        tuition_international=63255,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=50000,
        official_url="https://www.caltech.edu",
        description="Small, elite STEM-focused university. Very research intensive.",
        cs_ranking=7,
        engineering_ranking=4,
    ),
    UniversityEntry(
        name="Columbia University",
        state="NY",
        campus_setting="URBAN",
        acceptance_rate=0.039,
        median_gpa=3.95,
        sat_25th=1480,
        sat_75th=1570,
        act_25th=34,
        act_75th=35,
        tuition_out_of_state=66139,
        tuition_international=66139,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=57000,
        official_url="https://www.columbia.edu",
        description="Ivy League university in NYC. Core curriculum, strong all fields.",
        cs_ranking=11,
    ),
    UniversityEntry(
        name="University of Pennsylvania",
        state="PA",
        campus_setting="URBAN",
        acceptance_rate=0.056,
        median_gpa=3.92,
        sat_25th=1470,
        sat_75th=1570,
        act_25th=33,
        act_75th=35,
        tuition_out_of_state=63452,
        tuition_international=63452,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=55000,
        official_url="https://www.upenn.edu",
        description="Ivy League in Philadelphia. Strong business (Wharton), engineering.",
        cs_ranking=15,
    ),
    UniversityEntry(
        name="Duke University",
        state="NC",
        campus_setting="SUBURBAN",
        acceptance_rate=0.054,
        median_gpa=3.92,
        sat_25th=1470,
        sat_75th=1570,
        act_25th=33,
        act_75th=35,
        tuition_out_of_state=66325,
        tuition_international=66325,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=56000,
        official_url="https://www.duke.edu",
        description="Top research university in Durham, NC. Strong in all fields.",
        cs_ranking=25,
    ),
    UniversityEntry(
        name="Northwestern University",
        state="IL",
        campus_setting="SUBURBAN",
        acceptance_rate=0.07,
        median_gpa=3.90,
        sat_25th=1450,
        sat_75th=1560,
        act_25th=33,
        act_75th=35,
        tuition_out_of_state=65997,
        tuition_international=65997,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=53000,
        official_url="https://www.northwestern.edu",
        description="Research university near Chicago. Strong journalism, engineering.",
        cs_ranking=28,
    ),
    UniversityEntry(
        name="University of Chicago",
        state="IL",
        campus_setting="URBAN",
        acceptance_rate=0.052,
        median_gpa=3.95,
        sat_25th=1490,
        sat_75th=1580,
        act_25th=34,
        act_75th=35,
        tuition_out_of_state=66939,
        tuition_international=66939,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=54000,
        official_url="https://www.uchicago.edu",
        description="Top research university. Rigorous academics, core curriculum.",
        cs_ranking=29,
    ),
    UniversityEntry(
        name="Brown University",
        state="RI",
        campus_setting="URBAN",
        acceptance_rate=0.050,
        median_gpa=3.92,
        sat_25th=1460,
        sat_75th=1570,
        act_25th=33,
        act_75th=35,
        tuition_out_of_state=66886,
        tuition_international=66886,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=56000,
        official_url="https://www.brown.edu",
        description="Ivy League with open curriculum. Strong liberal arts.",
        cs_ranking=22,
    ),
    UniversityEntry(
        name="Cornell University",
        state="NY",
        campus_setting="RURAL",
        acceptance_rate=0.076,
        median_gpa=3.90,
        sat_25th=1450,
        sat_75th=1560,
        act_25th=33,
        act_75th=35,
        tuition_out_of_state=66014,
        tuition_international=66014,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=52000,
        official_url="https://www.cornell.edu",
        description="Ivy League in Ithaca, NY. Strong engineering, hotel management.",
        cs_ranking=6,
        engineering_ranking=9,
    ),
    UniversityEntry(
        name="Rice University",
        state="TX",
        campus_setting="URBAN",
        acceptance_rate=0.079,
        median_gpa=3.90,
        sat_25th=1490,
        sat_75th=1570,
        act_25th=34,
        act_75th=36,
        tuition_out_of_state=58128,
        tuition_international=58128,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=50000,
        official_url="https://www.rice.edu",
        description="Top research university in Houston. Strong engineering, low tuition for private.",
        cs_ranking=18,
    ),
    UniversityEntry(
        name="Vanderbilt University",
        state="TN",
        campus_setting="URBAN",
        acceptance_rate=0.059,
        median_gpa=3.90,
        sat_25th=1460,
        sat_75th=1560,
        act_25th=33,
        act_75th=35,
        tuition_out_of_state=63946,
        tuition_international=63946,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=52000,
        official_url="https://www.vanderbilt.edu",
        description="Top research university in Nashville. Strong all fields.",
        cs_ranking=38,
    ),
    UniversityEntry(
        name="Johns Hopkins University",
        state="MD",
        campus_setting="URBAN",
        acceptance_rate=0.072,
        median_gpa=3.90,
        sat_25th=1480,
        sat_75th=1570,
        act_25th=34,
        act_75th=35,
        tuition_out_of_state=63340,
        tuition_international=63340,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=48000,
        official_url="https://www.jhu.edu",
        description="Top research university in Baltimore. World-renowned medical school.",
        cs_ranking=24,
    ),
    UniversityEntry(
        name="Carnegie Mellon University",
        state="PA",
        campus_setting="URBAN",
        acceptance_rate=0.110,
        median_gpa=3.90,
        sat_25th=1480,
        sat_75th=1570,
        act_25th=34,
        act_75th=35,
        tuition_out_of_state=62260,
        tuition_international=62260,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=45000,
        official_url="https://www.cmu.edu",
        description="Top tech university in Pittsburgh. Best CS and robotics programs.",
        cs_ranking=3,
        engineering_ranking=6,
    ),
    
    # =========================================================================
    # TIER 3: Top Public Universities (In-State Tuition Benefits)
    # =========================================================================
    UniversityEntry(
        name="University of California, Berkeley",
        state="CA",
        campus_setting="URBAN",
        acceptance_rate=0.113,
        median_gpa=3.89,
        sat_25th=1310,
        sat_75th=1530,
        act_25th=29,
        act_75th=35,
        tuition_in_state=14312,
        tuition_out_of_state=44066,
        tuition_international=47066,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=25000,
        is_public=True,
        official_url="https://www.berkeley.edu",
        description="Top public research university. Excellent CS and engineering.",
        cs_ranking=4,
        engineering_ranking=3,
    ),
    UniversityEntry(
        name="University of California, Los Angeles",
        state="CA",
        campus_setting="URBAN",
        acceptance_rate=0.087,
        median_gpa=3.90,
        sat_25th=1290,
        sat_75th=1510,
        act_25th=29,
        act_75th=34,
        tuition_in_state=13804,
        tuition_out_of_state=44830,
        tuition_international=47830,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=22000,
        is_public=True,
        official_url="https://www.ucla.edu",
        description="Top public university in LA. Strong all fields, great campus life.",
        cs_ranking=12,
    ),
    UniversityEntry(
        name="University of California, San Diego",
        state="CA",
        campus_setting="SUBURBAN",
        acceptance_rate=0.24,
        median_gpa=3.85,
        sat_25th=1280,
        sat_75th=1490,
        act_25th=28,
        act_75th=34,
        tuition_in_state=14046,
        tuition_out_of_state=44408,
        tuition_international=47408,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=20000,
        is_public=True,
        official_url="https://www.ucsd.edu",
        description="Research-focused UC campus. Strong STEM, bioengineering.",
        cs_ranking=16,
    ),
    UniversityEntry(
        name="Georgia Institute of Technology",
        state="GA",
        campus_setting="URBAN",
        acceptance_rate=0.16,
        median_gpa=3.90,
        sat_25th=1390,
        sat_75th=1540,
        act_25th=31,
        act_75th=35,
        tuition_in_state=12682,
        tuition_out_of_state=33964,
        tuition_international=33964,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=15000,
        is_public=True,
        official_url="https://www.gatech.edu",
        description="Top public tech university. Excellent engineering, CS programs.",
        cs_ranking=5,
        engineering_ranking=5,
    ),
    UniversityEntry(
        name="University of Michigan, Ann Arbor",
        state="MI",
        campus_setting="URBAN",
        acceptance_rate=0.176,
        median_gpa=3.88,
        sat_25th=1340,
        sat_75th=1530,
        act_25th=31,
        act_75th=34,
        tuition_in_state=16736,
        tuition_out_of_state=57273,
        tuition_international=57273,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=25000,
        is_public=True,
        official_url="https://umich.edu",
        description="Top public research university. Strong engineering, business.",
        cs_ranking=10,
        engineering_ranking=7,
    ),
    UniversityEntry(
        name="University of Texas at Austin",
        state="TX",
        campus_setting="URBAN",
        acceptance_rate=0.29,
        median_gpa=3.80,
        sat_25th=1230,
        sat_75th=1480,
        act_25th=27,
        act_75th=33,
        tuition_in_state=11998,
        tuition_out_of_state=41070,
        tuition_international=41070,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=15000,
        is_public=True,
        official_url="https://www.utexas.edu",
        description="Flagship Texas university. Strong CS, engineering, business.",
        cs_ranking=9,
        engineering_ranking=10,
    ),
    UniversityEntry(
        name="University of Illinois Urbana-Champaign",
        state="IL",
        campus_setting="SUBURBAN",
        acceptance_rate=0.45,
        median_gpa=3.75,
        sat_25th=1270,
        sat_75th=1490,
        act_25th=28,
        act_75th=34,
        tuition_in_state=16866,
        tuition_out_of_state=36068,
        tuition_international=36068,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=18000,
        is_public=True,
        official_url="https://illinois.edu",
        description="Top public engineering school. Strong CS program.",
        cs_ranking=5,
        engineering_ranking=8,
    ),
    UniversityEntry(
        name="University of Washington",
        state="WA",
        campus_setting="URBAN",
        acceptance_rate=0.48,
        median_gpa=3.78,
        sat_25th=1240,
        sat_75th=1460,
        act_25th=28,
        act_75th=33,
        tuition_in_state=12076,
        tuition_out_of_state=41997,
        tuition_international=41997,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=15000,
        is_public=True,
        official_url="https://www.washington.edu",
        description="Top Pacific NW university. Strong CS, ties to tech industry.",
        cs_ranking=6,
    ),
    UniversityEntry(
        name="University of Virginia",
        state="VA",
        campus_setting="SUBURBAN",
        acceptance_rate=0.189,
        median_gpa=3.88,
        sat_25th=1360,
        sat_75th=1510,
        act_25th=31,
        act_75th=34,
        tuition_in_state=20342,
        tuition_out_of_state=56837,
        tuition_international=56837,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=27000,
        is_public=True,
        official_url="https://www.virginia.edu",
        description="Historic public university. Strong business, law, liberal arts.",
        cs_ranking=30,
    ),
    UniversityEntry(
        name="University of North Carolina at Chapel Hill",
        state="NC",
        campus_setting="SUBURBAN",
        acceptance_rate=0.17,
        median_gpa=3.88,
        sat_25th=1310,
        sat_75th=1490,
        act_25th=29,
        act_75th=34,
        tuition_in_state=8998,
        tuition_out_of_state=36776,
        tuition_international=36776,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=22000,
        is_public=True,
        official_url="https://www.unc.edu",
        description="Top public university. Strong journalism, business, sciences.",
        cs_ranking=31,
    ),
    UniversityEntry(
        name="University of Wisconsin-Madison",
        state="WI",
        campus_setting="URBAN",
        acceptance_rate=0.49,
        median_gpa=3.75,
        sat_25th=1280,
        sat_75th=1460,
        act_25th=28,
        act_75th=33,
        tuition_in_state=10720,
        tuition_out_of_state=39427,
        tuition_international=39427,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=16000,
        is_public=True,
        official_url="https://www.wisc.edu",
        description="Top Midwest public university. Strong research, CS, engineering.",
        cs_ranking=13,
    ),
    UniversityEntry(
        name="Purdue University",
        state="IN",
        campus_setting="SUBURBAN",
        acceptance_rate=0.53,
        median_gpa=3.70,
        sat_25th=1180,
        sat_75th=1430,
        act_25th=26,
        act_75th=33,
        tuition_in_state=9992,
        tuition_out_of_state=28794,
        tuition_international=28794,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=14000,
        is_public=True,
        official_url="https://www.purdue.edu",
        description="Top engineering school. Strong aerospace, CS, affordable.",
        cs_ranking=19,
        engineering_ranking=11,
    ),
    UniversityEntry(
        name="University of Maryland, College Park",
        state="MD",
        campus_setting="SUBURBAN",
        acceptance_rate=0.44,
        median_gpa=3.78,
        sat_25th=1310,
        sat_75th=1490,
        act_25th=29,
        act_75th=34,
        tuition_in_state=11505,
        tuition_out_of_state=40306,
        tuition_international=40306,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=15000,
        is_public=True,
        official_url="https://www.umd.edu",
        description="Top public near DC. Strong CS, engineering, proximity to tech jobs.",
        cs_ranking=17,
    ),
    UniversityEntry(
        name="Ohio State University",
        state="OH",
        campus_setting="URBAN",
        acceptance_rate=0.53,
        median_gpa=3.70,
        sat_25th=1220,
        sat_75th=1420,
        act_25th=27,
        act_75th=32,
        tuition_in_state=11936,
        tuition_out_of_state=35019,
        tuition_international=35019,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=14000,
        is_public=True,
        official_url="https://www.osu.edu",
        description="Large public university. Strong business, engineering, big campus.",
        cs_ranking=33,
    ),
    UniversityEntry(
        name="Pennsylvania State University",
        state="PA",
        campus_setting="SUBURBAN",
        acceptance_rate=0.54,
        median_gpa=3.65,
        sat_25th=1160,
        sat_75th=1360,
        act_25th=26,
        act_75th=31,
        tuition_in_state=19286,
        tuition_out_of_state=38824,
        tuition_international=38824,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=12000,
        is_public=True,
        official_url="https://www.psu.edu",
        description="Large public university. Strong engineering, business.",
        cs_ranking=35,
    ),
    UniversityEntry(
        name="University of Florida",
        state="FL",
        campus_setting="SUBURBAN",
        acceptance_rate=0.23,
        median_gpa=3.80,
        sat_25th=1320,
        sat_75th=1470,
        act_25th=29,
        act_75th=33,
        tuition_in_state=6380,
        tuition_out_of_state=28658,
        tuition_international=28658,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=16000,
        is_public=True,
        official_url="https://www.ufl.edu",
        description="Top Florida public. Very affordable, strong all fields.",
        cs_ranking=26,
    ),
    UniversityEntry(
        name="University of California, Irvine",
        state="CA",
        campus_setting="SUBURBAN",
        acceptance_rate=0.21,
        median_gpa=3.80,
        sat_25th=1195,
        sat_75th=1420,
        act_25th=26,
        act_75th=32,
        tuition_in_state=13752,
        tuition_out_of_state=44308,
        tuition_international=47308,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=18000,
        is_public=True,
        official_url="https://uci.edu",
        description="Growing UC campus. Strong CS, gaming industry ties.",
        cs_ranking=23,
    ),
    UniversityEntry(
        name="University of California, Davis",
        state="CA",
        campus_setting="SUBURBAN",
        acceptance_rate=0.37,
        median_gpa=3.80,
        sat_25th=1170,
        sat_75th=1400,
        act_25th=26,
        act_75th=32,
        tuition_in_state=14495,
        tuition_out_of_state=44249,
        tuition_international=47249,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=18000,
        is_public=True,
        official_url="https://www.ucdavis.edu",
        description="UC campus strong in agriculture, biological sciences.",
        cs_ranking=34,
    ),
    UniversityEntry(
        name="University of California, Santa Barbara",
        state="CA",
        campus_setting="SUBURBAN",
        acceptance_rate=0.26,
        median_gpa=3.82,
        sat_25th=1230,
        sat_75th=1460,
        act_25th=27,
        act_75th=33,
        tuition_in_state=14391,
        tuition_out_of_state=44145,
        tuition_international=47145,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=18000,
        is_public=True,
        official_url="https://www.ucsb.edu",
        description="Beautiful coastal campus. Strong physics, engineering.",
        cs_ranking=27,
    ),
    UniversityEntry(
        name="Texas A&M University",
        state="TX",
        campus_setting="SUBURBAN",
        acceptance_rate=0.63,
        median_gpa=3.68,
        sat_25th=1140,
        sat_75th=1370,
        act_25th=25,
        act_75th=31,
        tuition_in_state=12734,
        tuition_out_of_state=40966,
        tuition_international=40966,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=13000,
        is_public=True,
        official_url="https://www.tamu.edu",
        description="Large Texas university. Strong engineering, traditions.",
        cs_ranking=32,
        engineering_ranking=12,
    ),
    UniversityEntry(
        name="Virginia Tech",
        state="VA",
        campus_setting="RURAL",
        acceptance_rate=0.57,
        median_gpa=3.72,
        sat_25th=1190,
        sat_75th=1390,
        act_25th=26,
        act_75th=32,
        tuition_in_state=14726,
        tuition_out_of_state=35380,
        tuition_international=35380,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=12000,
        is_public=True,
        official_url="https://www.vt.edu",
        description="Top engineering school. Strong CS, beautiful campus.",
        cs_ranking=36,
        engineering_ranking=13,
    ),
    UniversityEntry(
        name="North Carolina State University",
        state="NC",
        campus_setting="URBAN",
        acceptance_rate=0.47,
        median_gpa=3.75,
        sat_25th=1260,
        sat_75th=1430,
        act_25th=28,
        act_75th=32,
        tuition_in_state=9101,
        tuition_out_of_state=30869,
        tuition_international=30869,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=13000,
        is_public=True,
        official_url="https://www.ncsu.edu",
        description="Research Triangle university. Strong engineering, CS.",
        cs_ranking=37,
    ),
    UniversityEntry(
        name="Rutgers University-New Brunswick",
        state="NJ",
        campus_setting="SUBURBAN",
        acceptance_rate=0.66,
        median_gpa=3.60,
        sat_25th=1230,
        sat_75th=1440,
        act_25th=27,
        act_75th=33,
        tuition_in_state=16536,
        tuition_out_of_state=35832,
        tuition_international=35832,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=14000,
        is_public=True,
        official_url="https://www.rutgers.edu",
        description="NJ flagship university. Diverse, close to NYC.",
        cs_ranking=39,
    ),
    UniversityEntry(
        name="University of Minnesota Twin Cities",
        state="MN",
        campus_setting="URBAN",
        acceptance_rate=0.75,
        median_gpa=3.60,
        sat_25th=1270,
        sat_75th=1440,
        act_25th=27,
        act_75th=32,
        tuition_in_state=15844,
        tuition_out_of_state=36402,
        tuition_international=36402,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=13000,
        is_public=True,
        official_url="https://twin-cities.umn.edu",
        description="Large Midwest research university. Strong engineering.",
        cs_ranking=40,
    ),
    
    # =========================================================================
    # TIER 4: Hidden Gems (Lesser-known but excellent programs)
    # =========================================================================
    UniversityEntry(
        name="Harvey Mudd College",
        state="CA",
        campus_setting="SUBURBAN",
        acceptance_rate=0.135,
        median_gpa=3.95,
        sat_25th=1490,
        sat_75th=1570,
        act_25th=33,
        act_75th=35,
        tuition_out_of_state=63825,
        tuition_international=63825,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=45000,
        official_url="https://www.hmc.edu",
        description="Elite STEM liberal arts. Exceptional CS and engineering.",
        cs_ranking=21,
    ),
    UniversityEntry(
        name="Williams College",
        state="MA",
        campus_setting="RURAL",
        acceptance_rate=0.097,
        median_gpa=3.90,
        sat_25th=1420,
        sat_75th=1560,
        act_25th=32,
        act_75th=35,
        tuition_out_of_state=65490,
        tuition_international=65490,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=57000,
        official_url="https://www.williams.edu",
        description="#1 liberal arts college. Beautiful rural campus.",
    ),
    UniversityEntry(
        name="Pomona College",
        state="CA",
        campus_setting="SUBURBAN",
        acceptance_rate=0.069,
        median_gpa=3.92,
        sat_25th=1420,
        sat_75th=1550,
        act_25th=32,
        act_75th=35,
        tuition_out_of_state=61660,
        tuition_international=61660,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=55000,
        official_url="https://www.pomona.edu",
        description="Top liberal arts in California. Part of Claremont colleges.",
    ),
    UniversityEntry(
        name="Swarthmore College",
        state="PA",
        campus_setting="SUBURBAN",
        acceptance_rate=0.074,
        median_gpa=3.90,
        sat_25th=1410,
        sat_75th=1550,
        act_25th=32,
        act_75th=35,
        tuition_out_of_state=62070,
        tuition_international=62070,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=54000,
        official_url="https://www.swarthmore.edu",
        description="Elite liberal arts near Philadelphia. Strong academics.",
    ),
    UniversityEntry(
        name="Middlebury College",
        state="VT",
        campus_setting="RURAL",
        acceptance_rate=0.131,
        median_gpa=3.85,
        sat_25th=1360,
        sat_75th=1530,
        act_25th=31,
        act_75th=34,
        tuition_out_of_state=63456,
        tuition_international=63456,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=50000,
        official_url="https://www.middlebury.edu",
        description="Top liberal arts in Vermont. Strong languages, environmental studies.",
    ),
    UniversityEntry(
        name="Wellesley College",
        state="MA",
        campus_setting="SUBURBAN",
        acceptance_rate=0.127,
        median_gpa=3.88,
        sat_25th=1380,
        sat_75th=1520,
        act_25th=31,
        act_75th=34,
        tuition_out_of_state=65676,
        tuition_international=65676,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=52000,
        official_url="https://www.wellesley.edu",
        description="Top women's college. Cross-registration with MIT.",
    ),
    UniversityEntry(
        name="Colby College",
        state="ME",
        campus_setting="RURAL",
        acceptance_rate=0.097,
        median_gpa=3.85,
        sat_25th=1340,
        sat_75th=1510,
        act_25th=31,
        act_75th=34,
        tuition_out_of_state=65480,
        tuition_international=65480,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=50000,
        official_url="https://www.colby.edu",
        description="Liberal arts in Maine. Growing STEM programs.",
    ),
    UniversityEntry(
        name="Grinnell College",
        state="IA",
        campus_setting="RURAL",
        acceptance_rate=0.099,
        median_gpa=3.85,
        sat_25th=1330,
        sat_75th=1520,
        act_25th=30,
        act_75th=34,
        tuition_out_of_state=63644,
        tuition_international=63644,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=48000,
        official_url="https://www.grinnell.edu",
        description="Top liberal arts in Iowa. Self-governance, open curriculum.",
    ),
    UniversityEntry(
        name="Carleton College",
        state="MN",
        campus_setting="RURAL",
        acceptance_rate=0.165,
        median_gpa=3.88,
        sat_25th=1370,
        sat_75th=1530,
        act_25th=31,
        act_75th=34,
        tuition_out_of_state=65460,
        tuition_international=65460,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=47000,
        official_url="https://www.carleton.edu",
        description="Top liberal arts in Minnesota. Strong sciences.",
    ),
    UniversityEntry(
        name="Claremont McKenna College",
        state="CA",
        campus_setting="SUBURBAN",
        acceptance_rate=0.085,
        median_gpa=3.88,
        sat_25th=1400,
        sat_75th=1530,
        act_25th=32,
        act_75th=34,
        tuition_out_of_state=63555,
        tuition_international=63555,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=51000,
        official_url="https://www.cmc.edu",
        description="Liberal arts focused on economics, government, leadership.",
    ),
    UniversityEntry(
        name="University of Rochester",
        state="NY",
        campus_setting="SUBURBAN",
        acceptance_rate=0.39,
        median_gpa=3.78,
        sat_25th=1340,
        sat_75th=1510,
        act_25th=30,
        act_75th=34,
        tuition_out_of_state=62680,
        tuition_international=62680,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=42000,
        official_url="https://www.rochester.edu",
        description="Research university with flexible curriculum. Strong optics, music.",
        cs_ranking=42,
    ),
    UniversityEntry(
        name="Case Western Reserve University",
        state="OH",
        campus_setting="URBAN",
        acceptance_rate=0.30,
        median_gpa=3.82,
        sat_25th=1340,
        sat_75th=1510,
        act_25th=30,
        act_75th=34,
        tuition_out_of_state=59166,
        tuition_international=59166,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=42000,
        official_url="https://case.edu",
        description="Research university in Cleveland. Strong engineering, biomedical.",
        cs_ranking=45,
    ),
    UniversityEntry(
        name="Northeastern University",
        state="MA",
        campus_setting="URBAN",
        acceptance_rate=0.065,
        median_gpa=3.85,
        sat_25th=1430,
        sat_75th=1540,
        act_25th=32,
        act_75th=35,
        tuition_out_of_state=62158,
        tuition_international=62158,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=38000,
        official_url="https://www.northeastern.edu",
        description="Co-op focused university in Boston. Strong CS, career outcomes.",
        cs_ranking=41,
    ),
    UniversityEntry(
        name="Boston University",
        state="MA",
        campus_setting="URBAN",
        acceptance_rate=0.14,
        median_gpa=3.80,
        sat_25th=1360,
        sat_75th=1500,
        act_25th=31,
        act_75th=34,
        tuition_out_of_state=65168,
        tuition_international=65168,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=40000,
        official_url="https://www.bu.edu",
        description="Large research university in Boston. Strong all fields.",
        cs_ranking=44,
    ),
    UniversityEntry(
        name="New York University",
        state="NY",
        campus_setting="URBAN",
        acceptance_rate=0.12,
        median_gpa=3.78,
        sat_25th=1370,
        sat_75th=1530,
        act_25th=31,
        act_75th=34,
        tuition_out_of_state=62250,
        tuition_international=62250,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=False,
        avg_aid_package=35000,
        official_url="https://www.nyu.edu",
        description="Global university in NYC. Strong business, arts, tech.",
        cs_ranking=43,
    ),
    UniversityEntry(
        name="University of Southern California",
        state="CA",
        campus_setting="URBAN",
        acceptance_rate=0.094,
        median_gpa=3.85,
        sat_25th=1400,
        sat_75th=1530,
        act_25th=32,
        act_75th=34,
        tuition_out_of_state=67853,
        tuition_international=67853,
        need_blind_domestic=True,
        need_blind_international=False,
        meets_full_need=True,
        avg_aid_package=45000,
        official_url="https://www.usc.edu",
        description="Private research university in LA. Strong film, engineering, CS.",
        cs_ranking=20,
    ),
]


async def populate_universities():
    """Main population function."""
    import sys
    sys.path.insert(0, "/Users/luisabrantes/Documents/Code/collegeListAI/backend")
    
    from app.infrastructure.db.vector_service import VectorService
    from supabase import create_client
    from app.config.settings import settings
    
    logger.info(f"Starting population with {len(UNIVERSITIES)} universities...")
    
    # Initialize services
    vector_service = VectorService()
    supabase = vector_service.supabase
    
    success_count = 0
    error_count = 0
    
    for i, uni in enumerate(UNIVERSITIES, 1):
        try:
            # Build description for embedding
            description_parts = [
                uni.name,
                uni.description,
                f"Located in {uni.state}",
                f"{uni.campus_setting.lower()} campus",
            ]
            
            if uni.cs_ranking:
                description_parts.append(f"CS ranking #{uni.cs_ranking}")
            if uni.engineering_ranking:
                description_parts.append(f"Engineering ranking #{uni.engineering_ranking}")
            if uni.need_blind_international:
                description_parts.append("Need-blind for international students")
            if uni.is_public:
                description_parts.append(f"Public university with in-state tuition ${uni.tuition_in_state:,.0f}")
            
            full_description = ". ".join(description_parts)
            
            # Generate embedding
            logger.info(f"[{i}/{len(UNIVERSITIES)}] Generating embedding for {uni.name}...")
            embedding = await vector_service.generate_document_embedding(full_description)
            
            # Prepare data for universities_master
            master_data = {
                "name": uni.name,
                "state": uni.state,
                "campus_setting": uni.campus_setting,
                "acceptance_rate": uni.acceptance_rate,
                "median_gpa": uni.median_gpa,
                "sat_25th": uni.sat_25th,
                "sat_75th": uni.sat_75th,
                "act_25th": uni.act_25th,
                "act_75th": uni.act_75th,
                "tuition_in_state": uni.tuition_in_state,
                "tuition_out_of_state": uni.tuition_out_of_state,
                "tuition_international": uni.tuition_international,
                "need_blind_domestic": uni.need_blind_domestic,
                "need_blind_international": uni.need_blind_international,
                "meets_full_need": uni.meets_full_need,
                "avg_aid_package": uni.avg_aid_package,
                "official_url": uni.official_url,
                "data_source": "manual_curated",
            }
            
            # Remove None values
            master_data = {k: v for k, v in master_data.items() if v is not None}
            
            # Insert into universities_master
            try:
                supabase.table("universities_master").upsert(
                    master_data,
                    on_conflict="name"
                ).execute()
                logger.info(f"  ✓ Added to universities_master")
            except Exception as e:
                logger.warning(f"  ⚠ universities_master error (may not exist yet): {e}")
            
            # Prepare data for colleges_cache
            cache_content = {
                "description": uni.description,
                "acceptance_rate": uni.acceptance_rate,
                "median_gpa": uni.median_gpa,
                "state": uni.state,
                "campus_setting": uni.campus_setting,
                "need_blind_international": uni.need_blind_international,
                "meets_full_need": uni.meets_full_need,
                "cs_ranking": uni.cs_ranking,
                "is_public": uni.is_public,
            }
            
            # Insert into colleges_cache with embedding
            supabase.table("colleges_cache").upsert({
                "name": uni.name,
                "content": json.dumps(cache_content),
                "embedding": embedding,
            }, on_conflict="name").execute()
            
            logger.info(f"  ✓ Added to colleges_cache with embedding")
            success_count += 1
            
            # Rate limit delay
            await asyncio.sleep(0.5)
            
        except Exception as e:
            logger.error(f"  ✗ Failed: {e}")
            error_count += 1
    
    logger.info("=" * 60)
    logger.info(f"Population complete!")
    logger.info(f"  ✓ Success: {success_count}")
    logger.info(f"  ✗ Errors: {error_count}")
    logger.info("=" * 60)


if __name__ == "__main__":
    asyncio.run(populate_universities())
